title: Motion Planning with Renew
description: Simulation guide of the research work conducted in the paper "Multi-robot Motion Planning based on Nets-within-Nets Modeling and Simulation"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://Sof16.github.io/MotionPlanningNwN

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Sof16/MotionPlanningNwN
